### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ojuschugh1** [nilsjennissen/mistral#2]
Hi , I got this error while running it-:

NameError: name 'text' is not defined
Traceback:
File "C:\Program Files\Python310\lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 541, in _run_script
    exec(code, module.__dict__)
File "C:\Users\ojchug\b\mistral\main.py", line 253, in <module>
    if text is not None:

How to solve this ?

Thanks and Regards

**Comment by DamOPC** [comment]
Hi @ojuschugh1 , 
I'm facing the same issue. Did you manage to solve this error ?
Thanks and regards

**Comment by nilsjennissen** [comment]
Thanks for pointing out the issue!
Updated the repo with a slight change. Refactoring 'text' to 'transcript' worked for now.

**Comment by DamOPC** [comment]
wow, that's a really quick response and update.
Thank you very much @nilsjennissen !
